export interface IScsoProducts {
  IBrand1: string
  IBrand2: string
  IBrand3: string
  IBrand4: string
  ItemG1: string
  ItemG2: string
  ItemG3: string
  ItemG4: string
  Item_Number: string
  ProductName: string
  ItemGroup: string
  Unit: string
  Price: number
  Sale_Tax: string
  Underdelivery: number
  Overdelivery: number
  Product_ActiveStatus: string
  UpdateDate: Date
  CreateDate: Date
  Status_SalesBots: number
  DPL_newItem: string
  DPL_ClassId: string
  DPL_StockDay: string
  DPL_MaximumOrder: number
  DPL_MinimumOrder: number
  DPL_ReorderPoint: number
  DPL_DateForOT: string
  DPL_DateForLP: string
  DPL_SB_DESCRIPTION: string
  DPL_SB_DESCRIPTIONTHAI: string
  DPL_SB_MODEL: string
  DPL_SB_BRAND: string
  DPL_SB_COLOR: string
  DPL_SB_COLORTH: string
  DPL_SB_PICTURE: string
  ITEMNAV: string
  DPL_STATUSITEM: string
  CHANNEL_ITEM: string
  DPL_Major: string
  DPL_Sub: string
  TYPE_BRAND: string
}
